title: "Nazarii Sheremet"
description: "Nazarii Sheremet personal website"
about: "I'm Software Developer. Working with Ruby/MRuby/Rust/Go/C/C++. Geek. Husband."
location: "Eastern Europe, Ukraine"
email: nazarii.sheremet@gmail.com
baseurl: ""

url: "https://nsheremet.pw"
enforce_ssl: "nsheremet.pw" # replace by your site's url

twitter_username: nsheremet
github_username:  nsheremet
author: "Nazarii Sheremet"

# google analytics tracking code, please change the value
g_analytics: "UA-72591400-1"

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
