# Site settings
title: Nazarii Sheremet
description: 'Husband, Geek, Software Engineer'
url: 'http://sheremet.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Nazarii Sheremet'
  email: nazar@sheremet.com
  twitter_username: xo8bit
  github_username:  xo8bit
  linkedin_username:  nsheremet

# Build settings
destination: _site
paginate: 1
permalink: /:categories/:title/
# markdown: markdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
